const assert = require('node:assert/strict');
const fs = require('node:fs');

const script = fs.readFileSync('apps/web/script.js', 'utf8');
const html = fs.readFileSync('apps/web/index.html', 'utf8');
const style = fs.readFileSync('apps/web/style.css', 'utf8');

assert.match(html, /data-view="dashboard-panel"/);
assert.match(html, /Dashboard phân tích kết quả tìm kiếm/);
assert.match(html, /class="dashboard-header-row"/);
assert.match(html, /class="dashboard-title-icon"[\s\S]{0,140}data-feather="bar-chart-2"/);
assert.match(html, /class="dashboard-context-bar"[\s\S]{0,220}data-feather="filter"/);
assert.match(html, /Bộ lọc đang áp dụng:/);
assert.match(html, /data-dashboard-kpi="total_awarded_value"/);
assert.match(html, /id="dashboard-province-map"/);
assert.match(html, /id="dashboard-top-products"/);
assert.match(html, /class="dashboard-products-measure"/);
assert.doesNotMatch(html, /Số gói thầu có chứa sản phẩm\./);
assert.match(html, /id="dashboard-timeline-chart"/);
assert.match(html, /id="dashboard-price-chart"/);
assert.match(html, /id="dashboard-top-investors"/);
assert.match(html, /class="dashboard-widget-title"[\s\S]{0,160}data-feather="map-pin"/);
assert.match(html, /class="dashboard-widget-title"[\s\S]{0,160}data-feather="bar-chart-2"/);
assert.match(html, /class="dashboard-widget-title"[\s\S]{0,160}data-feather="trending-up"/);
assert.match(style, /\.dashboard-main-grid[\s\S]{0,180}grid-auto-rows: clamp\(300px, 34vh, 320px\)/);
assert.match(style, /\.dashboard-main-grid \{[\s\S]{0,120}grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(style, /\.dashboard-secondary-grid[\s\S]{0,180}grid-auto-rows: clamp\(220px, 25vh, 250px\)/);
assert.match(style, /#dashboard-province-map svg[\s\S]{0,120}display: block;[\s\S]{0,120}width: calc\(100% - 196px\);[\s\S]{0,100}height: 100%;/);
assert.match(style, /\.dashboard-map-widget \.dashboard-widget-head[\s\S]{0,100}border-bottom: 0/);
assert.match(script, /function hideNoDataMessage\(canvasId\)[\s\S]{0,240}msg\.remove\(\)/);
assert.match(style, /\.province-map-legend-items[\s\S]{0,120}flex-direction: column/);
assert.match(style, /#dashboard-province-map \.province-map-legend[\s\S]{0,180}width: min\(184px, 30%\);[\s\S]{0,100}padding: 8px 9px/);
assert.match(style, /#dashboard-province-map \.province-map-legend-swatch[\s\S]{0,160}width: 14px[\s\S]{0,60}height: 14px/);
assert.match(style, /#dashboard-province-map \.province-map-legend-label[\s\S]{0,100}font-size: 10\.5px/);
assert.doesNotMatch(style, /province-map-legend-scale|province-map-legend-labels/);
assert.match(style, /\.dashboard-product-bar[\s\S]{0,260}grid-template-columns: 26px minmax\(145px, 0\.85fr\) minmax\(120px, 1\.4fr\) 38px/);
assert.match(style, /\.dashboard-product-track[\s\S]{0,220}grid-column: 3[\s\S]{0,100}height: 18px/);
assert.doesNotMatch(style, /dashboard-product-bar::before/);
assert.doesNotMatch(script, /--bar-width/);
assert.match(script, /fill\.style\.setProperty\('--product-bar-color', PROVINCE_MAP_BUCKET_COLORS\[colorIndex\]\)/);
assert.match(style, /\.dashboard-products[\s\S]{0,160}justify-content: space-between/);
assert.match(style, /\.dashboard-product-row\.is-selected \.dashboard-product-bar[\s\S]{0,180}box-shadow: inset 0 0 0 1px var\(--dashboard-navy\)/);
assert.doesNotMatch(style, /saturate\(1\.15\) brightness\(0\.82\)/);
assert.match(style, /\.dashboard-selection-bar\[hidden\][\s\S]{0,60}display: none/);
assert.match(style, /\.dashboard-selection-chip-label[\s\S]{0,180}text-overflow: ellipsis/);
assert.match(style, /\.dashboard-header-row[\s\S]{0,180}grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\)/);
assert.match(style, /\.dashboard-context-bar[\s\S]{0,220}min-height: 42px/);
assert.doesNotMatch(html, /dashboard-status|Phân tích toàn bộ kết quả phù hợp/);
assert.doesNotMatch(script, /setDashboardStatus|Phân tích toàn bộ kết quả phù hợp/);
assert.doesNotMatch(html, /dashboard-kpi-unit/);
assert.match(style, /\.dashboard-kpi-icon[\s\S]{0,220}width: 44px[\s\S]{0,80}height: 44px/);
assert.match(style, /\.dashboard-kpi-label[\s\S]{0,120}color: var\(--dashboard-navy\)/);
assert.match(style, /\.dashboard-kpi-card strong[\s\S]{0,160}color: var\(--dashboard-navy\)/);
assert.match(style, /\.legacy-pagination\.is-dashboard-hidden\s*\{\s*display: none/);

assert.match(script, /function buildDashboardAnalyticsRequest\(request = currentQueryRequest, selection = dashboardSelection\)/);
assert.match(script, /columnFilters: request\?\.columnFilters \|\| \{\}/);
assert.match(script, /dashboardSelection: \{/);
assert.match(script, /getAuthorizedFetch\(\)\(`\$\{API_BASE_URL\}\/api\/dashboard-analytics`/);
assert.doesNotMatch(script, /refreshDashboardAnalytics[\s\S]{0,1800}requireAuthenticatedSession\('login', 'full_query'\)/);
assert.match(script, /dashboardAnalyticsController\?\.abort\(\)/);
assert.match(script, /function setDashboardSelection\(key, value\)/);
assert.match(script, /onProvinceSelect: province => setDashboardSelection\('province', province\)/);
assert.match(script, /setDashboardSelection\('product', product\.name\)/);
assert.match(script, /setDashboardSelection\('investor', investor\.name\)/);
assert.match(script, /function syncDashboardSelectionVisuals\(\)/);
assert.match(script, /row\.dataset\.dashboardProduct = product\.name/);
assert.match(script, /row\.dataset\.dashboardInvestor = investor\.name/);
assert.match(script, /const nextValue = value \? String\(value\)\.trim\(\) : ''/);
assert.match(script, /dashboardAnalyticsVersion \+= 1;[\s\S]{0,120}refreshDashboardAnalytics\.lastRequestKey = ''/);
assert.match(script, /const controller = new AbortController\(\)/);
assert.match(script, /signal: controller\.signal/);
assert.match(script, /if \(refreshDashboardAnalytics\.lastBaseKey && refreshDashboardAnalytics\.lastBaseKey !== baseKey\) \{\s*resetDashboardSelection\(\);/);
assert.match(script, /function getDashboardBaseRequest\(request = currentQueryRequest\)[\s\S]{0,260}delete base\.page;[\s\S]{0,80}delete base\.limit;/);
assert.match(script, /if \(!hasActiveQueryFilters\(currentQueryRequest\)[\s\S]{0,360}renderDashboardEmpty\(\);/);
assert.match(script, /const leavingDashboard = activeButton\?\.getAttribute\('data-view'\) === 'dashboard-panel'/);
assert.match(script, /path\.setAttribute\('role', 'button'\)/);
assert.match(script, /path\.addEventListener\('keydown', event =>/);
assert.match(script, /legacy-pagination[^\n]*is-dashboard-hidden/);
assert.match(script, /Tổng giá trị trúng thầu/);
const selectionResetSource = script.slice(
  script.indexOf('function resetDashboardSelection'),
  script.indexOf('function getDashboardBaseRequest')
);
assert.doesNotMatch(selectionResetSource, /currentQueryRequest/);
assert.match(script, /function renderDashboardEmpty\(/);
assert.match(script, /tension: 0/);
assert.match(script, /dashboard-context-chip-label/);
assert.match(script, /function getDashboardSearchKeyword\(request = \{\}\)/);
assert.match(script, /const keywordFields = \[/);
assert.match(script, /searchForm\.fieldLabel\(fieldName\)/);
assert.match(script, /crossGroupProductKeyword/);
assert.match(script, /goodsKeyword/);
assert.doesNotMatch(script, /function formatDashboardFilterValue/);
assert.doesNotMatch(script, /function formatDashboardFilterLabel/);
assert.match(style, /--dashboard-navy: #122e5a/);
assert.match(style, /--dashboard-blue: #0f62d6/);
assert.match(script, /const PROVINCE_MAP_BUCKET_COLORS = \[/);
assert.match(script, /'#70acef'[\s\S]{0,80}'#dde2e6'/);
assert.match(script, /mapNoData: '#f2f4f6'/);
assert.match(script, /function getNiceProvinceScaleStep\(maxValue, targetBucketCount = 7\)/);
assert.match(script, /function buildProvinceMapColorBuckets\(values = \[\]\)/);
assert.match(script, /Math\.ceil\(rawUpper \/ roundingStep\) \* roundingStep/);
assert.doesNotMatch(script, /min: 500_000_000/);
assert.match(script, /const quantileIndex = Math\.min/);
assert.match(script, /function appendFeaturedProvinceLabels\(svg, valueByProvince\)/);
assert.match(script, /function getProvinceMainlandAnchor\(svg, path, fallbackBox\)/);
assert.match(script, /const labelY = anchorY/);
assert.match(script, /const titleSize = 18 \* pixelsToUnits;[\s\S]{0,80}const valueSize = 18 \* pixelsToUnits/);
assert.match(script, /preserveAspectRatio', 'xMidYMid meet'/);
assert.match(script, /getComputedTextLength/);
assert.match(script, /connector\.setAttribute\('x2', String\(labelX\)\)/);
assert.match(script, /const lineGap = 6 \* pixelsToUnits/);
assert.match(script, /const labelGap = 88 \* pixelsToUnits/);
assert.match(script, /anchor\.setAttribute\('r', String\(6 \* pixelsToUnits\)\)/);
assert.match(style, /\.dashboard-widget-title[\s\S]{0,180}color: var\(--dashboard-navy\)/);
assert.match(style, /\.dashboard-widget-title svg[\s\S]{0,180}color: var\(--dashboard-blue\)/);
assert.match(style, /\.dashboard-widget-head h3[\s\S]{0,120}font-size: 16px/);
assert.match(style, /\.vietnam-province-map[\s\S]{0,320}background: transparent/);
assert.match(style, /\.province-map-feature-label[\s\S]{0,180}pointer-events: none/);
assert.match(style, /#dashboard-province-map svg[\s\S]{0,180}width: calc\(100% - 196px\)/);
assert.match(style, /#dashboard-province-map \.province-map-legend-label[\s\S]{0,100}font-size: 10\.5px/);
assert.doesNotMatch(html, /Phân bổ theo địa điểm trong toàn bộ kết quả phù hợp/);
assert.match(style, /\.dashboard-context-chip-label[\s\S]{0,160}text-overflow: ellipsis/);
assert.match(style, /color: #1d78e9;[\s\S]{0,50}background: #dcecff/);

console.log('Dashboard analytics contract passed');
