'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..', '..');
const formSource = fs.readFileSync(path.join(root, 'apps/web/typesense-search-form.js'), 'utf8');
const chatSource = fs.readFileSync(path.join(root, 'apps/web/ai-search-chat.js'), 'utf8');
const indexSource = fs.readFileSync(path.join(root, 'apps/web/index.html'), 'utf8');
const styleSource = fs.readFileSync(path.join(root, 'apps/web/style.css'), 'utf8');
const scriptSource = fs.readFileSync(path.join(root, 'apps/web/script.js'), 'utf8');
const netlifySource = fs.readFileSync(path.join(root, 'netlify.toml'), 'utf8');
const legacyEmbeddedAiPattern = /data-ai-message|renderAiSearch|bindAiEvents|state\.ai|ai-search-panel/;
const assistantMarkupStart = indexSource.indexOf('<div class="workspace-actions toolbar-actions">');
const assistantMarkupEnd = indexSource.indexOf('<script src="https://accounts.google.com/gsi/client"', assistantMarkupStart);
const assistantMarkup = indexSource.slice(assistantMarkupStart, assistantMarkupEnd);

assert.doesNotMatch(formSource, legacyEmbeddedAiPattern);
assert.doesNotMatch(indexSource, legacyEmbeddedAiPattern);
assert.doesNotMatch(scriptSource, legacyEmbeddedAiPattern);
assert.doesNotMatch(indexSource, /id="ai-search-launcher"/);
assert.doesNotMatch(chatSource, /ai-search-launcher/);
assert.doesNotMatch(styleSource, /ai-search-launcher/);
assert.match(indexSource, /id="ai-search-chat"/);
assert.match(indexSource, /src="ai-search-chat\.js"/);
assert.match(indexSource, /<button[^>]+id="open-ai-search"[^>]+aria-label="Tìm kiếm bằng AI"[^>]+title="Tìm kiếm bằng AI"/);
assert.match(assistantMarkup, /id="open-filter-panel"[\s\S]*?<\/button>\s*<button[^>]+id="open-ai-search"[\s\S]*?<\/button>\s*<button[^>]+id="open-insight-drawer"/);
assert.match(styleSource, /\.result-table-tabs \.toolbar-actions > #open-ai-search\s*\{[\s\S]*?background: var\(--color-primary-dark\)[\s\S]*?color: var\(--color-primary-heavy-light\)/);
assert.match(styleSource, /\.result-table-tabs \.toolbar-actions > :is\([\s\S]*?#open-ai-search[\s\S]*?\)\s*\{[\s\S]*?border-radius: 20px/);
assert.doesNotMatch(styleSource, /body:not\(\.landing-active\) \.action-btn,[\s\S]*?border-radius: 10px !important/);
assert.doesNotMatch(styleSource, /body:not\(\.landing-active\) \.btn-meta-simple,[\s\S]*?border-radius: 10px !important/);
assert.match(styleSource, /\.result-table-tabs \.toolbar-actions > #open-ai-search:hover,[\s\S]*?\.result-table-tabs \.toolbar-actions > #open-ai-search\.is-open\s*\{[\s\S]*?background: var\(--color-primary\)/);
assert.match(styleSource, /\.result-table-tabs \.toolbar-actions > :is\([\s\S]*?#open-filter-panel,[\s\S]*?#open-ai-search,[\s\S]*?#open-insight-drawer[\s\S]*?\) \{[\s\S]*?width: 34px[\s\S]*?height: 34px/);
assert.doesNotMatch(styleSource, /\.workspace-actions \.ai-search-toolbar-btn/);
assert.doesNotMatch(styleSource, /\.ai-search-toolbar-btn\s*\{/);
assert.doesNotMatch(indexSource, /ai-search-toolbar-btn/);
assert.match(styleSource, /\.ai-search-toolbar-mark\s*\{[\s\S]*?display:\s*block;[\s\S]*?transform:\s*translateY\(1px\)/);
assert.match(assistantMarkup, /<h2 id="ai-search-chat-title">(?:Trợ lý AI|Tìm kiếm bằng AI)<\/h2>/);
assert.match(assistantMarkup, /class="ai-chat-avatar"/);
assert.doesNotMatch(assistantMarkup, /data-ai-chat-menu|data-ai-chat-menu-content|data-ai-chat-clear|Xóa cuộc trò chuyện/);
assert.match(chatSource, /const openButton = document\.getElementById\('open-ai-search'\)/);
assert.match(chatSource, /openButton\.addEventListener\('click', \(\) => setOpen\(!state\.open\)\)/);
assert.match(chatSource, /openButton\.setAttribute\('aria-expanded', String\(state\.open\)\)/);
assert.match(chatSource, /data-ai-chat-close[\s\S]*?setOpen\(false\)/);
assert.match(chatSource, /event\.key === 'Escape' && state\.open/);
assert.match(chatSource, /document\.addEventListener\('pointerdown', event => \{[\s\S]*?panel\.contains\(event\.target\)[\s\S]*?openButton\.contains\(event\.target\)[\s\S]*?setOpen\(false\)/);
assert.match(assistantMarkup, /class="ai-chat-icon-button window-close-button" data-ai-chat-close/);
assert.match(styleSource, /\.btn-close,\s*\.window-close-button \{[\s\S]*?color: #647b8a/);
assert.match(styleSource, /\.btn-close:hover,\s*\.window-close-button:hover \{[\s\S]*?border-color: #c43d3d[\s\S]*?color: #c43d3d/);
assert.doesNotMatch(styleSource, /#filter-panel \.btn-close/);
assert.doesNotMatch(styleSource, /ai-chat-icon-button\.window-close-button/);
assert.doesNotMatch(styleSource, /ai-chat-icon-button\[data-ai-chat-close\]/);
assert.match(assistantMarkup, /placeholder="Nhập yêu cầu tìm kiếm…"/);
assert.match(assistantMarkup, /rows="1"/);
assert.equal((assistantMarkup.match(/<textarea id="ai-chat-input"/g) || []).length, 1);
assert.match(assistantMarkup, /<label class="sr-only" for="ai-chat-input">/);
assert.doesNotMatch(assistantMarkup, /Đang tải hạn mức AI/);
assert.match(styleSource, /\.ai-search-chat \.sr-only\s*\{/);
assert.doesNotMatch(assistantMarkup, />Xóa</);
assert.doesNotMatch(assistantMarkup, />Đóng</);
assert.doesNotMatch(assistantMarkup, />Gửi</);
[
  'Tôi có thể giúp tìm kiếm nhanh hơn.',
  'Mô tả điều bạn cần tìm; mỗi tin nhắn là một yêu cầu độc lập.',
  'Mô tả yêu cầu tìm kiếm',
  'Enter để gửi · Shift+Enter để xuống dòng · Mỗi tin nhắn là một yêu cầu mới',
  'BIDFinder hiểu yêu cầu như sau',
  'Xem trước: tìm thấy',
  'Chỉnh sửa điều kiện'
].forEach(text => {
  assert.doesNotMatch(assistantMarkup, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.doesNotMatch(chatSource, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
});
assert.match(indexSource, /src="typesense-search-form\.js"/);
assert.match(indexSource, /src="script\.js"/);
assert.match(indexSource, /href="style\.css(?:\?[^\"]*)?"/);
assert.match(netlifySource, /for = "\/\*"/);
assert.match(netlifySource, /Cache-Control = "public, max-age=0, must-revalidate"/);
assert.equal((indexSource.match(/data-ai-chat-group=/g) || []).length, 3);
assert.match(indexSource, /Hàng hóa/);
assert.match(indexSource, /Thuốc/);
assert.match(indexSource, /Dược liệu/);
assert.match(styleSource, /\.ai-chat-groups \{[^}]*gap: 8px/);
assert.match(styleSource, /\.ai-chat-groups button \{[^}]*border: 1(?:\.5)?px solid/);
assert.match(styleSource, /\.ai-chat-groups \{[^}]*width: 100%/);
assert.match(styleSource, /\.ai-chat-groups button \{[^}]*flex: 1 1 0/);
assert.match(styleSource, /\.ai-chat-groups button \{[^}]*min-height: 36px/);
assert.match(styleSource, /\.ai-chat-groups button \{[^}]*border-radius: 20px/);
assert.doesNotMatch(styleSource, /\.ai-chat-groups \{[^}]*border:/);
assert.doesNotMatch(styleSource, /\.ai-chat-input-row \{[^}]*border:/);
assert.match(styleSource, /\.ai-chat-input-row textarea \{[^}]*border: 1px solid[^}]*border-radius: 20px/);
assert.match(styleSource, /\.ai-chat-messages \{[^}]*background: #fff/);
assert.match(styleSource, /\.ai-chat-input-row textarea \{[^}]*background: #f7fafb/);
assert.match(styleSource, /\.ai-chat-send \{[^}]*background: transparent[^}]*color: #127495/);
assert.match(styleSource, /\.ai-chat-send:hover:not\(:disabled\) \{[^}]*background: transparent/);
assert.match(indexSource, /<path d="M2\.01 21 23 12 2\.01 3 2 10l15 2-15 2z" fill="currentColor"\/>/);
assert.match(styleSource, /\.ai-chat-send svg \{[^}]*width: 24px[^}]*height: 24px/);
assert.match(styleSource, /\.ai-chat-input-row textarea:focus \{[^}]*outline: none[^}]*border-color: #cbd9de[^}]*box-shadow: none/);
assert.match(styleSource, /\.ai-search-chat \{[\s\S]*?width: min\(390px/);
assert.match(chatSource, /const panelWidth = Math\.min\(390/);
assert.match(styleSource, /\.ai-search-chat \{[\s\S]*?top: var\(--ai-chat-top, 16px\)/);
assert.match(styleSource, /\.ai-search-chat \{[\s\S]*?height: min\(560px/);
assert.match(chatSource, /function positionPanel\(\)/);
assert.match(chatSource, /openButton\.getBoundingClientRect\(\)/);
assert.match(chatSource, /--ai-chat-top/);
assert.match(chatSource, /messagesRoot\.scrollTop = messagesRoot\.scrollHeight/);
assert.match(assistantMarkup, /<button[^>]+data-ai-chat-group="goods"/);
assert.match(assistantMarkup, /<button[^>]+data-ai-chat-group="medicines"/);
assert.match(assistantMarkup, /<button[^>]+data-ai-chat-group="traditional"/);

assert.match(chatSource, /\/api\/ai\/search-preview/);
assert.match(chatSource, /body: JSON\.stringify\(\{ group: item\.group, message: item\.message \}\)/);
assert.doesNotMatch(chatSource, /history.*body|body: JSON\.stringify\(state\.history/);
assert.doesNotMatch(chatSource, /editingId|editPlan|editPlanMarkup|collectEditedPlan|saveEditedPlan|startEdit|data-ai-chat-action|Chỉnh sửa/);
assert.match(chatSource, /COMPILED_REQUEST_MARKER/);
assert.match(chatSource, /new CustomEvent\('apply-filters'/);
assert.match(chatSource, /executeSearch\(item\.id\)/);
assert.match(chatSource, /\/api\/ai\/usage/);
assert.match(chatSource, /async function loadUsage\(force = false\)/);
assert.match(chatSource, /if \(!force && state\.usageRequestId > 0\) return;/);
assert.match(chatSource, /refreshUsage: \(\) => loadUsage\(true\)/);
assert.match(chatSource, /remaining_percent/);
assert.match(chatSource, /const usageLevel = remaining >= 70 \? 'healthy' : remaining >= 30 \? 'warning' : 'critical'/);
assert.match(chatSource, /usageRoot\.removeAttribute\('data-usage-level'\)/);
assert.match(chatSource, /usageRoot\.dataset\.usageLevel = usageLevel/);
assert.match(chatSource, /localStorage/);
assert.match(chatSource, /usageStatus: 'loading'/);
assert.match(chatSource, /state\.usageStatus = 'unavailable'/);
assert.match(chatSource, /usageRoot\.replaceChildren\(\)/);
assert.doesNotMatch(chatSource, /usageRoot\.textContent = '—'/);
assert.match(chatSource, /Hạn mức AI hiện không khả dụng/);
assert.match(chatSource, /setTimeout\([\s\S]*?1200/);
assert.match(chatSource, /if \(response\.ok && payload\?\.success && updateUsage\(payload\)\)/);
assert.match(chatSource, /if \(state\.usageStatus !== 'loading'\) return;/);
assert.match(chatSource, /state\.usageStatus = 'available'/);
assert.match(chatSource, /ai-chat-usage-fill/);
assert.match(chatSource, /--ai-chat-usage-value/);
assert.match(chatSource, /aria-valuenow/);
assert.match(chatSource, /event\.key === 'Enter' && !event\.shiftKey/);
assert.match(chatSource, /composer\.requestSubmit\(\)/);
assert.doesNotMatch(chatSource, /formatCount|resultLine|Xem kết quả|Không có kết quả/);
assert.doesNotMatch(chatSource, /assistant\.plan\.explanation/);
assert.match(chatSource, /warningMessages/);
assert.match(chatSource, /Yêu cầu chưa rõ: có thể là tên thuốc, hoạt chất hoặc từ viết tắt/);
assert.match(chatSource, /resizeInput/);
assert.doesNotMatch(chatSource, /clearHistory|data-ai-chat-clear|data-ai-chat-menu/);
assert.match(chatSource, /new CustomEvent\('apply-filters'/);
assert.match(scriptSource, /const PANEL_CONFIG/);
assert.match(scriptSource, /open-filter-panel/);
assert.match(chatSource, /Hàng hóa/);
assert.match(chatSource, /Thuốc/);
assert.match(chatSource, /Dược liệu/);
assert.match(styleSource, /\.ai-chat-message\.user \{[^}]*border-radius: 10px;/);
assert.match(styleSource, /\.ai-chat-message\.assistant \{[^}]*background: #f2f7f9/);
assert.match(styleSource, /\.ai-chat-usage-fill \{[^}]*width: var\(--ai-chat-usage-value/);
assert.match(styleSource, /\.ai-chat-usage\[data-usage-level="healthy"\] \.ai-chat-usage-fill \{[^}]*background: #2f8f5b/);
assert.match(styleSource, /\.ai-chat-usage\[data-usage-level="warning"\] \.ai-chat-usage-fill \{[^}]*background: #d29a22/);
assert.match(styleSource, /\.ai-chat-usage\[data-usage-level="critical"\] \.ai-chat-usage-fill \{[^}]*background: #c74848/);
assert.match(styleSource, /\.ai-chat-exchange \{[^}]*gap: 12px[^}]*margin: 0 0 12px/);
assert.match(styleSource, /\.ai-chat-conditions li \{[^}]*align-items: baseline/);

assert.match(scriptSource, /const AI_COMPILED_REQUEST_MARKER/);
assert.match(scriptSource, /currentQueryRequest = payload\?\.\[AI_COMPILED_REQUEST_MARKER\]/);
assert.match(scriptSource, /\?\s*payload\s*:\s*enrichLegacyQueryRequest\(payload\);/);
assert.doesNotMatch(scriptSource, /console\.log\('Applying filters with query request:/);
assert.match(scriptSource, /filters: queryRequest\?\.filters \|\| \{\}/);

console.log('AI search UI contract passed');
